// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Models;

namespace StudentManagementSystem_CodeFirst.Migrations
{
    [DbContext(typeof(StudentManagementSystemContext))]
    partial class StudentManagementSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentManagementSystem.Models.Address", b =>
                {
                    b.Property<string>("AddressId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdminNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("AdminNo")
                        .IsUnique()
                        .HasFilter("[AdminNo] IS NOT NULL");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Diploma", b =>
                {
                    b.Property<string>("DiplomaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiplomaId");

                    b.ToTable("Diploma");

                    b.HasData(
                        new
                        {
                            DiplomaId = "C36",
                            Name = "Common ICT Programme"
                        },
                        new
                        {
                            DiplomaId = "C35",
                            Name = "Business & Financial Technology"
                        },
                        new
                        {
                            DiplomaId = "C43",
                            Name = "Business & Financial Technology"
                        },
                        new
                        {
                            DiplomaId = "C54",
                            Name = "Cybersecurity & Digital Forensics "
                        },
                        new
                        {
                            DiplomaId = "C80",
                            Name = "Infocomm & Security "
                        },
                        new
                        {
                            DiplomaId = "C85",
                            Name = "Information Technology  "
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Module", b =>
                {
                    b.Property<string>("ModuleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModuleId");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            ModuleId = "IT1010",
                            Name = "Data Analysis & Visualisation"
                        },
                        new
                        {
                            ModuleId = "IT1020",
                            Name = "Fundamentals of Innovation & Enterprise"
                        },
                        new
                        {
                            ModuleId = "IT1030",
                            Name = "Infocomm Security"
                        },
                        new
                        {
                            ModuleId = "IT1040",
                            Name = "Network Technology"
                        },
                        new
                        {
                            ModuleId = "IT1050",
                            Name = "Web Development"
                        },
                        new
                        {
                            ModuleId = "IT1060",
                            Name = "Programming Essentials"
                        },
                        new
                        {
                            ModuleId = "ITX150",
                            Name = "App Development Project"
                        });
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Student", b =>
                {
                    b.Property<string>("AdminNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiplomaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminNo");

                    b.HasIndex("DiplomaId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.StudentModules", b =>
                {
                    b.Property<string>("AdminNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModuleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AdminNo", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("StudentModules");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Address", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Student", "Student")
                        .WithOne("Address")
                        .HasForeignKey("StudentManagementSystem.Models.Address", "AdminNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Student", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Diploma", "Diploma")
                        .WithMany("Students")
                        .HasForeignKey("DiplomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diploma");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.StudentModules", b =>
                {
                    b.HasOne("StudentManagementSystem.Models.Student", "Student")
                        .WithMany("StudentModules")
                        .HasForeignKey("AdminNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementSystem.Models.Module", "Module")
                        .WithMany("StudentModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Diploma", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Module", b =>
                {
                    b.Navigation("StudentModules");
                });

            modelBuilder.Entity("StudentManagementSystem.Models.Student", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("StudentModules");
                });
#pragma warning restore 612, 618
        }
    }
}
